// main.dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:genui/genui.dart';
import 'package:genui_google_generative_ai/genui_google_generative_ai.dart';
import 'package:logging/logging.dart'; // For GenUI logging

// For getting API key securely. In a real app, this would be more robust.
// For web, use 'api_key/web_get_api_key.dart', for others 'api_key/io_get_api_key.dart'.
import 'api_key_helper.dart'; // You would create this file

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Load environment variables from .env (if present).
  // This ensures `getApiKey()` can read `GEMINI_API_KEY` via dotenv.
  await loadEnv();

  // Configure GenUI logging for debugging
  configureGenUiLogging(level: Level.ALL);

  runApp(const LearningApp());
}

class LearningApp extends StatelessWidget {
  const LearningApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'GenUI Learning App',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const LearningScreen(),
    );
  }
}

class LearningScreen extends StatefulWidget {
  const LearningScreen({super.key});

  @override
  State<LearningScreen> createState() => _LearningScreenState();
}

class _LearningScreenState extends State<LearningScreen> {
  final TextEditingController _textController = TextEditingController();
  final List<ChatMessage> _messages = []; // Stores conversation history
  late final GenUiConversation _genUiConversation;
  late final A2uiMessageProcessor _a2uiMessageProcessor;
  String? _initErrorMessage;
  final ScrollController _scrollController = ScrollController();

  @override
  void initState() {
    super.initState();

    try {
      // 1. Initialize A2uiMessageProcessor with a Catalog
      final Catalog coreCatalog = CoreCatalogItems.asCatalog();
      _a2uiMessageProcessor = A2uiMessageProcessor(catalogs: [coreCatalog]);

      // Define the system instruction to guide the AI's behavior.
      final systemInstruction = '''
        You are an expert educational assistant. Your goal is to help the user learn about any topic they request.
        When the user asks about a topic, provide a concise explanation and present relevant interactive UI elements
        (e.g., buttons for "More info," "Quiz me," "Example," or columns/cards to organize content).
        Always prioritize presenting information in UI components over plain text when possible.

        IMPORTANT: When you generate UI in a response, you MUST always create
        a new surface with a unique `surfaceId`. Do NOT reuse or update
        existing `surfaceId`s. Each UI response must be in its own new surface.

        ${GenUiPromptFragments.basicChat}''';

      // 2. Create a ContentGenerator instance.
      final ContentGenerator contentGenerator = GoogleGenerativeAiContentGenerator(
        catalog: coreCatalog,
        systemInstruction: systemInstruction,
        apiKey: getApiKey(),
      );

      // 3. Create the GenUiConversation to orchestrate the process.
      _genUiConversation = GenUiConversation(
        a2uiMessageProcessor: _a2uiMessageProcessor,
        contentGenerator: contentGenerator,
        onSurfaceAdded: _handleSurfaceAdded,
        onSurfaceUpdated: _handleSurfaceUpdated,
        onTextResponse: _onTextResponse,
        onError: (error) {
          genUiLogger.severe(
            'Error from content generator',
            error.error,
            error.stackTrace,
          );
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(content: Text('AI Error: ${error.error}')),
            );
          }
        },
      );
    } catch (e, st) {
      genUiLogger.severe('Initialization error', e, st);
      _initErrorMessage = e.toString();
      if (mounted) {
        WidgetsBinding.instance.addPostFrameCallback((_) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Initialization error: $_initErrorMessage')),
          );
        });
      }
    }
  }

  // Callback when a new UI surface is generated by the AI
  void _handleSurfaceAdded(SurfaceAdded update) {
    if (!mounted) return;
    setState(() {
      _messages.add(
        AiUiMessage(
          definition: update.definition,
          surfaceId: update.surfaceId,
        ),
      );
    });
    _scrollToBottom();
  }

  // Callback when an existing UI surface is updated by the AI
  void _handleSurfaceUpdated(SurfaceUpdated update) {
    // GenUiConversation already updates the internal list of messages.
    // We just need to trigger a rebuild to ensure UI reflects changes.
    if (!mounted) return;
    setState(() {
      // No explicit modification to _messages list here, as GenUiConversation handles it.
      // This setState simply ensures the UI rebuilds to pick up changes in existing GenUiSurface.
    });
    _scrollToBottom();
  }


  // Callback for AI text-only responses
  void _onTextResponse(String text) {
    if (!mounted) return;
    if (text.trim().isNotEmpty) {
      setState(() {
        _messages.add(AiTextMessage.text(text));
      });
      _scrollToBottom();
    }
  }

  // Sends the user's message to the GenUI conversation
  void _sendMessage() {
    final String text = _textController.text.trim();
    if (text.isEmpty || _genUiConversation.isProcessing.value) {
      return;
    }
    _textController.clear();

    // Add user message to local display
    setState(() {
      _messages.add(UserMessage.text(text));
    });
    _scrollToBottom();

    // Send request to the AI
    unawaited(_genUiConversation.sendRequest(UserMessage.text(text)));
  }

  // Scrolls the message list to the bottom
  void _scrollToBottom() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (_scrollController.hasClients) {
        _scrollController.animateTo(
          _scrollController.position.maxScrollExtent,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeOut,
        );
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('GenUI Learning Assistant')),
      body: SafeArea(
        child: Column(
          children: [
            Expanded(
              child: ListView.builder(
                controller: _scrollController,
                itemCount: _messages.length,
                itemBuilder: (context, index) {
                  final message = _messages[index];
                  // Display different message types
                  switch (message) {
                    case AiUiMessage():
                    // Render AI-generated UI surface using GenUiSurface.
                    // The `host` is the A2uiMessageProcessor, which manages
                    // the state of the UI definition for `surfaceId`.
                      return Card( // Wrap in a Card for better visual separation
                        margin: const EdgeInsets.symmetric(vertical: 8.0, horizontal: 16.0),
                        child: Padding(
                          padding: const EdgeInsets.all(8.0),
                          child: GenUiSurface(
                            key: message.uiKey, // Important for Flutter to distinguish surfaces
                            host: _genUiConversation.host,
                            surfaceId: message.surfaceId,
                          ),
                        ),
                      );
                    case AiTextMessage():
                    // Display plain AI text
                      return ChatBubble(
                        text: message.text,
                        isUser: false,
                      );
                    case UserMessage():
                    // Display user's text input
                      return ChatBubble(
                        text: message.text,
                        isUser: true,
                      );
                    default:
                      return const SizedBox.shrink();
                  }
                },
              ),
            ),
            // Show a loading indicator when the AI is processing
            ValueListenableBuilder<bool>(
              valueListenable: _genUiConversation.isProcessing,
              builder: (_, isProcessing, __) {
                if (!isProcessing) return const SizedBox.shrink();
                return const Padding(
                  padding: EdgeInsets.all(8.0),
                  child: LinearProgressIndicator(),
                );
              },
            ),
            // User input row
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: Row(
                children: [
                  Expanded(
                    child: TextField(
                      controller: _textController,
                      decoration: const InputDecoration(
                        hintText: 'Ask me about a topic...',
                        border: OutlineInputBorder(),
                      ),
                      onSubmitted: (_) => _sendMessage(),
                      enabled: !_genUiConversation.isProcessing.value, // Disable input when processing
                    ),
                  ),
                  const SizedBox(width: 8),
                  IconButton(
                    icon: const Icon(Icons.send),
                    onPressed: _sendMessage,
                    color: Theme.of(context).primaryColor,
                    disabledColor: Colors.grey,
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  @override
  void dispose() {
    _textController.dispose();
    _genUiConversation.dispose(); // Dispose of the conversation
    _scrollController.dispose();
    super.dispose();
  }
}

// Simple widget for displaying chat bubbles
class ChatBubble extends StatelessWidget {
  final String text;
  final bool isUser;

  const ChatBubble({super.key, required this.text, required this.isUser});

  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: isUser ? Alignment.centerRight : Alignment.centerLeft,
      child: Container(
        margin: const EdgeInsets.symmetric(vertical: 4.0, horizontal: 12.0),
        padding: const EdgeInsets.all(12.0),
        decoration: BoxDecoration(
          color: isUser ? Colors.blueAccent : Colors.grey[300],
          borderRadius: BorderRadius.circular(18.0),
        ),
        child: Text(
          text,
          style: TextStyle(
            color: isUser ? Colors.white : Colors.black87,
          ),
        ),
      ),
    );
  }
}



